### ISSUE TITLE
Support scrambling

### ISSUE THREAD

**Issue by peterp** [snaplet/copycat#15]
I think of scrambling as a generic method for non-specific transformations. The idea is that a given string is randomly shifted:

`the DOG ate the cheese!` becomes `shx SAS weq sss snmwlx`. I would love to be able to specify characters that should not be transformed:

`copycat.scramble(input, { preserve: ['@', ' ', '!'] })`

**Comment by peterp** [comment]
A person may want to use this is they need to preserve the visual weight, or layout of textual content.

**Comment by justinvdm** [comment]
> copycat.scramble(input, { preserve: ['@', ' ', '!'] })

I really like this API!

**Comment by d3v0ps** [comment]
would be possible to use word dictionary instead of just a random string?

**Comment by justinvdm** [comment]
Added in #18!
