### ISSUE TITLE
Support slugs?

### ISSUE THREAD

**Issue by zomars** [snaplet/copycat#17]
I see that your username function may generate usernames with dots in them. In our use case we need to generate username with only alphanumeric characters and maybe dashes and underscores.

**Comment by justinvdm** [comment]
Hey @zomars, thanks for the request. I'm going back and forth on whether to add an option for `copycat.username()` for this.

What do you think about just using other copycat functions on your side to put this together? e.g.

```js
const username = x => `${copycat.firstName(x)}-${copycat.lastName(x)}${copycat.integer(x, { min: 2, max: 99 })}`
```

**Comment by zomars** [comment]
This can work for now. Thanks for the insights 🙏🏽

**Comment by justinvdm** [comment]
Awesome, thanks @zomars :) Closing for now then.
