### ISSUE TITLE
The latest release displayed on GitHub is misleading

### ISSUE THREAD

**Issue by Jolg42** [snaplet/copycat#47]
See https://github.com/snaplet/copycat/releases

<img width="951" alt="Screenshot 2023-11-02 at 09 48 21" src="https://github.com/snaplet/copycat/assets/1328733/394a69c9-4194-44cd-858b-ae2821d0fe41">
<img width="298" alt="Screenshot 2023-11-02 at 09 47 42" src="https://github.com/snaplet/copycat/assets/1328733/4974ad05-9e2e-4906-b5e7-df49a876e508">

From npm https://www.npmjs.com/package/@snaplet/copycat
<img width="968" alt="Screenshot 2023-11-02 at 09 49 48" src="https://github.com/snaplet/copycat/assets/1328733/210b0a02-3994-4a69-81d3-ec4cab628ace">

**Comment by justinvdm** [comment]
Hey @Jolg42, thanks for bringing this up. We can fix this so that the releases are showing up on github too.

**Comment by justinvdm** [comment]
@Jolg42 we'll be adding a release for `0.18.1` (with a changelog entry) shortly. We'll also add future releases at https://github.com/snaplet/copycat/releases (each with a changelog entry). I think that should be it for this one, so I'm going to go ahead and close it.
