### ISSUE TITLE
It would be nice to have a changelog

### ISSUE THREAD

**Issue by Jolg42** [snaplet/copycat#48]
Since there are no information as releases, see https://github.com/snaplet/copycat/releases
And no changelog file.

The only way to review what changed is to do a git diff between tags at the moment.

Example Renovate PR
https://github.com/prisma/prisma/pull/21718

Usually it would also list the changes, but it's empty 
The only way to review is to review https://renovatebot.com/diffs/npm/@snaplet%2fcopycat/0.17.3/0.18.1

**Comment by justinvdm** [comment]
Hey @Jolg42, totally agree, we need a changelog, especially considering the recent breaking change. I'm hoping my answer in https://github.com/snaplet/copycat/issues/49#issuecomment-1790371672 covers this enough, so I'm going to close this one and we can discuss further in #49. We're also tracking this as a ticket internally so we can prioritise it.

**Comment by Jolg42** [comment]
Nice! Thanks for the good work on copycat 💚
