### ISSUE TITLE
Feature request: Localization support

### ISSUE THREAD

**Issue by dbrekelmans** [snaplet/copycat#60]
Address information and phone numbers can look very different, based on the country.

It would be great to be able to pass the requested locale as an option for those data types.
As an example, Faker supports quite a few locales: https://github.com/faker-js/faker?tab=readme-ov-file#-localization

**Comment by justinvdm** [comment]
Hi @dbrekelmans, localization support would indeed be great. Its been on our radar for some time now, but I'm not sure if we can prioritise it at the moment.

If it helps, until then you can still use copycat's primitives (e.g. `oneOf()`, `int()`) to generate data that is valid for a particular locale. For example, you could use it along with faker's locale-based data:
```ts
import { fakerDE as faker } from '@faker-js/faker'
import { copycat } from '@snaplet/copycat'

const city = input => copycat.oneOf(input, faker.definitions.location.city_name)
```

**Comment by dbrekelmans** [comment]
That works for me, thanks 👍

**Comment by justinvdm** [comment]
Great 👍 I'll close this for now, as we're tracking this internally for prioritising it. Thank you!
