### ISSUE TITLE
fn oneOf extend options

### ISSUE THREAD

**Issue by T04435** [snaplet/copycat#61]
extend [oneOf](https://github.com/snaplet/copycat?tab=readme-ov-file#copycatoneofinput-values-options) options to include a sequential: boolean

this will make the fn get the item from values in a sequential order

```js
copycat.oneOf(input, ['foo','bar','baz'], {sequential: true})
for input
'2' => 'foo'
'one' => 'bar'
'0' => 'baz'
'pick' => 'foo'
//...repeat
```

Sometimes we care about the order the output is copied.

**Comment by justinvdm** [comment]
Hey @T04435, if I'm following, the idea here relies on the ordering in which inputs are given - e.g. if `'one'` was given before `2`, it would map to `'foo'` instead. In contrast, copycat doesn't rely on the order in which values are given, and there's no state affecting what the results may be. So it's sort of at odds with what we intended to achieve with copycat.

The use case does make sense though, I'm just not sure if it belongs in copycat.

Could this maybe be solved simply enough without copycat?

```js
const createOneOfSequential = (values) => {
    let counter = 0
    const cache = new Map()

    const oneOfSequential = (input) => {
      if (cache.has(input)) {
          return cache.get(input)
      }

      const result = values[counter++ % values.length]
      cache.set(input, result)

      return result
    }

    return oneOfSequential
}

const oneOfSequential = createOneOfSequential(["foo", 'bar', 'baz'])

oneOfSequential('2')  // foo
oneOfSequential('one')  // bar
oneOfSequential('0')  // baz
oneOfSequential('pick')  // foo
oneOfSequential('0')  // baz
```
